#!/bin/bash -e
if [[ ! -f "/home/spark-48049699-3175-4c07-b65a-3c/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-48049699-3175-4c07-b65a-3c/tmp/uv/uv_0.6.10_linux_arm64" "$@"
